### ISSUE TITLE
Tracking: Changes to generators

### ISSUE THREAD

**Issue by imphil** [olofk/fusesoc#455]
Currently, generators are only able to produce source files, which are then added to the file list. For advanced use cases, e.g. in OpenTitan, that's not enough. We currently are running a patched version of FuseSoC for OpenTitan and I'm working on changing a couple more things. This issue is tracking progress on that.

These changes will be changing the behavior of generators, and should therefor go into the next major release.

High priority:
- [ ] Resolve dependencies for generator-created cores: #391
- [ ] Pass information about discovered cores to a generator (EDAM file change): #250
- [ ] Allow dependencies to generator-produced cores: #449 

Lower priority:
- [ ] #382

**Comment by olofk** [comment]
Is this still valid?

**Comment by imphil** [comment]
Probably yes, there is no way to do what OpenTitan needs with current FuseSoC releases.

**Comment by olofk** [comment]
We're dropping this as an alternative path was chosen
