### ISSUE TITLE
FuseSoC 2.0 tracking bug

### ISSUE THREAD

**Issue by olofk** [olofk/fusesoc#542]
FuseSoC 2.0 (with dropped support for CAPI1) should had been out for a while already, so let's list the things remaining to get this released. Writing the items I think are important to get done and hope for some discussion about what should be added to or removed from this list
* [x] Flow API support https://github.com/olofk/fusesoc/tree/flowapi
* [x] Default use flags in targets #502
* [x] Separate source dir for each target #493 #425 #366

**Comment by olofk** [comment]
Alright. All the big items are done for FuseSoC 2.0.0 Unless there are other things coming up soon, we're getting ready to release.

**Comment by olofk** [comment]
Fuck yeah! We did it
